// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetInfoRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetInfoResponse {
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Hop {
    #[prost(bytes = "vec", tag = "1")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub short_channel_id: u64,
    #[prost(uint64, tag = "3")]
    pub base_fee: u64,
    #[prost(uint64, tag = "4")]
    pub ppm_fee: u64,
    #[prost(uint64, tag = "5")]
    pub cltv_expiry_delta: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoutingHint {
    #[prost(message, repeated, tag = "1")]
    pub hops: ::prost::alloc::vec::Vec<Hop>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InvoiceRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub payment_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub amount_msat: u64,
    #[prost(uint64, optional, tag = "5")]
    pub expiry: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "6")]
    pub min_final_cltv_expiry: ::core::option::Option<u64>,
    #[prost(message, repeated, tag = "7")]
    pub routing_hints: ::prost::alloc::vec::Vec<RoutingHint>,
    #[prost(oneof = "invoice_request::Description", tags = "3, 4")]
    pub description: ::core::option::Option<invoice_request::Description>,
}
/// Nested message and enum types in `InvoiceRequest`.
pub mod invoice_request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Description {
        #[prost(string, tag = "3")]
        Memo(::prost::alloc::string::String),
        #[prost(bytes, tag = "4")]
        Hash(::prost::alloc::vec::Vec<u8>),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InvoiceResponse {
    #[prost(string, tag = "1")]
    pub bolt11: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InjectRequest {
    #[prost(string, tag = "1")]
    pub invoice: ::prost::alloc::string::String,
    #[prost(uint64, optional, tag = "2")]
    pub min_cltv_expiry: ::core::option::Option<u64>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct InjectResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListRequest {
    #[prost(oneof = "list_request::Constraint", tags = "1, 2")]
    pub constraint: ::core::option::Option<list_request::Constraint>,
}
/// Nested message and enum types in `ListRequest`.
pub mod list_request {
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct Pagination {
        /// Inclusive
        #[prost(int64, tag = "1")]
        pub index_start: i64,
        #[prost(uint64, tag = "2")]
        pub limit: u64,
    }
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Constraint {
        #[prost(bytes, tag = "1")]
        PaymentHash(::prost::alloc::vec::Vec<u8>),
        #[prost(message, tag = "2")]
        Pagination(Pagination),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Htlc {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(enumeration = "InvoiceState", tag = "2")]
    pub state: i32,
    #[prost(string, tag = "3")]
    pub scid: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub channel_id: u64,
    #[prost(uint64, tag = "5")]
    pub msat: u64,
    #[prost(uint64, tag = "6")]
    pub created_at: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Invoice {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(bytes = "vec", tag = "2")]
    pub payment_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub preimage: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, tag = "4")]
    pub invoice: ::prost::alloc::string::String,
    #[prost(enumeration = "InvoiceState", tag = "5")]
    pub state: i32,
    #[prost(uint64, tag = "6")]
    pub created_at: u64,
    #[prost(uint64, optional, tag = "8")]
    pub settled_at: ::core::option::Option<u64>,
    #[prost(message, repeated, tag = "7")]
    pub htlcs: ::prost::alloc::vec::Vec<Htlc>,
    #[prost(uint64, optional, tag = "9")]
    pub min_cltv_expiry: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListResponse {
    #[prost(message, repeated, tag = "1")]
    pub invoices: ::prost::alloc::vec::Vec<Invoice>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SettleRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub payment_preimage: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SettleResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub payment_hash: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CancelResponse {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CleanRequest {
    /// Clean everything older than age seconds
    #[prost(uint64, optional, tag = "1")]
    pub age: ::core::option::Option<u64>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CleanResponse {
    #[prost(uint64, tag = "1")]
    pub cleaned: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TrackRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub payment_hash: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TrackResponse {
    #[prost(enumeration = "InvoiceState", tag = "1")]
    pub state: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TrackAllRequest {
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub payment_hashes: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TrackAllResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub payment_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub bolt11: ::prost::alloc::string::String,
    #[prost(enumeration = "InvoiceState", tag = "3")]
    pub state: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OnionMessage {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(bytes = "vec", optional, tag = "2")]
    pub pathsecret: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(message, optional, tag = "3")]
    pub reply_blindedpath: ::core::option::Option<onion_message::ReplyBlindedPath>,
    #[prost(bytes = "vec", optional, tag = "4")]
    pub invoice_request: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "5")]
    pub invoice: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "6")]
    pub invoice_error: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(message, repeated, tag = "7")]
    pub unknown_fields: ::prost::alloc::vec::Vec<onion_message::UnknownField>,
}
/// Nested message and enum types in `OnionMessage`.
pub mod onion_message {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct ReplyBlindedPath {
        #[prost(bytes = "vec", optional, tag = "1")]
        pub first_node_id: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
        #[prost(string, optional, tag = "2")]
        pub first_scid: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(uint64, optional, tag = "3")]
        pub first_scid_dir: ::core::option::Option<u64>,
        #[prost(bytes = "vec", optional, tag = "4")]
        pub first_path_key: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
        #[prost(message, repeated, tag = "5")]
        pub hops: ::prost::alloc::vec::Vec<reply_blinded_path::Hop>,
    }
    /// Nested message and enum types in `ReplyBlindedPath`.
    pub mod reply_blinded_path {
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct Hop {
            #[prost(bytes = "vec", optional, tag = "1")]
            pub blinded_node_id: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
            #[prost(bytes = "vec", optional, tag = "2")]
            pub encrypted_recipient_data: ::core::option::Option<
                ::prost::alloc::vec::Vec<u8>,
            >,
        }
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct UnknownField {
        #[prost(uint64, tag = "1")]
        pub number: u64,
        #[prost(bytes = "vec", tag = "2")]
        pub value: ::prost::alloc::vec::Vec<u8>,
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct OnionMessageResponse {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(enumeration = "HookAction", tag = "2")]
    pub action: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum HookAction {
    Continue = 0,
    Resolve = 1,
}
impl HookAction {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Continue => "Continue",
            Self::Resolve => "Resolve",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Continue" => Some(Self::Continue),
            "Resolve" => Some(Self::Resolve),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum InvoiceState {
    Unpaid = 0,
    Accepted = 1,
    Paid = 2,
    Cancelled = 3,
}
impl InvoiceState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unpaid => "UNPAID",
            Self::Accepted => "ACCEPTED",
            Self::Paid => "PAID",
            Self::Cancelled => "CANCELLED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNPAID" => Some(Self::Unpaid),
            "ACCEPTED" => Some(Self::Accepted),
            "PAID" => Some(Self::Paid),
            "CANCELLED" => Some(Self::Cancelled),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod hold_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct HoldClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl HoldClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> HoldClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> HoldClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            HoldClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn get_info(
            &mut self,
            request: impl tonic::IntoRequest<super::GetInfoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetInfoResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/hold.Hold/GetInfo");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("hold.Hold", "GetInfo"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn invoice(
            &mut self,
            request: impl tonic::IntoRequest<super::InvoiceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::InvoiceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/hold.Hold/Invoice");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("hold.Hold", "Invoice"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn inject(
            &mut self,
            request: impl tonic::IntoRequest<super::InjectRequest>,
        ) -> std::result::Result<tonic::Response<super::InjectResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/hold.Hold/Inject");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("hold.Hold", "Inject"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn list(
            &mut self,
            request: impl tonic::IntoRequest<super::ListRequest>,
        ) -> std::result::Result<tonic::Response<super::ListResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/hold.Hold/List");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("hold.Hold", "List"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn settle(
            &mut self,
            request: impl tonic::IntoRequest<super::SettleRequest>,
        ) -> std::result::Result<tonic::Response<super::SettleResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/hold.Hold/Settle");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("hold.Hold", "Settle"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn cancel(
            &mut self,
            request: impl tonic::IntoRequest<super::CancelRequest>,
        ) -> std::result::Result<tonic::Response<super::CancelResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/hold.Hold/Cancel");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("hold.Hold", "Cancel"));
            self.inner.unary(req, path, codec).await
        }
        /// Cleans cancelled invoices
        pub async fn clean(
            &mut self,
            request: impl tonic::IntoRequest<super::CleanRequest>,
        ) -> std::result::Result<tonic::Response<super::CleanResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/hold.Hold/Clean");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("hold.Hold", "Clean"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn track(
            &mut self,
            request: impl tonic::IntoRequest<super::TrackRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::TrackResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/hold.Hold/Track");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("hold.Hold", "Track"));
            self.inner.server_streaming(req, path, codec).await
        }
        pub async fn track_all(
            &mut self,
            request: impl tonic::IntoRequest<super::TrackAllRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::TrackAllResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/hold.Hold/TrackAll");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("hold.Hold", "TrackAll"));
            self.inner.server_streaming(req, path, codec).await
        }
        pub async fn onion_messages(
            &mut self,
            request: impl tonic::IntoStreamingRequest<
                Message = super::OnionMessageResponse,
            >,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::OnionMessage>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/hold.Hold/OnionMessages");
            let mut req = request.into_streaming_request();
            req.extensions_mut().insert(GrpcMethod::new("hold.Hold", "OnionMessages"));
            self.inner.streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod hold_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with HoldServer.
    #[async_trait]
    pub trait Hold: std::marker::Send + std::marker::Sync + 'static {
        async fn get_info(
            &self,
            request: tonic::Request<super::GetInfoRequest>,
        ) -> std::result::Result<tonic::Response<super::GetInfoResponse>, tonic::Status>;
        async fn invoice(
            &self,
            request: tonic::Request<super::InvoiceRequest>,
        ) -> std::result::Result<tonic::Response<super::InvoiceResponse>, tonic::Status>;
        async fn inject(
            &self,
            request: tonic::Request<super::InjectRequest>,
        ) -> std::result::Result<tonic::Response<super::InjectResponse>, tonic::Status>;
        async fn list(
            &self,
            request: tonic::Request<super::ListRequest>,
        ) -> std::result::Result<tonic::Response<super::ListResponse>, tonic::Status>;
        async fn settle(
            &self,
            request: tonic::Request<super::SettleRequest>,
        ) -> std::result::Result<tonic::Response<super::SettleResponse>, tonic::Status>;
        async fn cancel(
            &self,
            request: tonic::Request<super::CancelRequest>,
        ) -> std::result::Result<tonic::Response<super::CancelResponse>, tonic::Status>;
        /// Cleans cancelled invoices
        async fn clean(
            &self,
            request: tonic::Request<super::CleanRequest>,
        ) -> std::result::Result<tonic::Response<super::CleanResponse>, tonic::Status>;
        /// Server streaming response type for the Track method.
        type TrackStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::TrackResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn track(
            &self,
            request: tonic::Request<super::TrackRequest>,
        ) -> std::result::Result<tonic::Response<Self::TrackStream>, tonic::Status>;
        /// Server streaming response type for the TrackAll method.
        type TrackAllStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::TrackAllResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn track_all(
            &self,
            request: tonic::Request<super::TrackAllRequest>,
        ) -> std::result::Result<tonic::Response<Self::TrackAllStream>, tonic::Status>;
        /// Server streaming response type for the OnionMessages method.
        type OnionMessagesStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::OnionMessage, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn onion_messages(
            &self,
            request: tonic::Request<tonic::Streaming<super::OnionMessageResponse>>,
        ) -> std::result::Result<
            tonic::Response<Self::OnionMessagesStream>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct HoldServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> HoldServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for HoldServer<T>
    where
        T: Hold,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/hold.Hold/GetInfo" => {
                    #[allow(non_camel_case_types)]
                    struct GetInfoSvc<T: Hold>(pub Arc<T>);
                    impl<T: Hold> tonic::server::UnaryService<super::GetInfoRequest>
                    for GetInfoSvc<T> {
                        type Response = super::GetInfoResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetInfoRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Hold>::get_info(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetInfoSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hold.Hold/Invoice" => {
                    #[allow(non_camel_case_types)]
                    struct InvoiceSvc<T: Hold>(pub Arc<T>);
                    impl<T: Hold> tonic::server::UnaryService<super::InvoiceRequest>
                    for InvoiceSvc<T> {
                        type Response = super::InvoiceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::InvoiceRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Hold>::invoice(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = InvoiceSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hold.Hold/Inject" => {
                    #[allow(non_camel_case_types)]
                    struct InjectSvc<T: Hold>(pub Arc<T>);
                    impl<T: Hold> tonic::server::UnaryService<super::InjectRequest>
                    for InjectSvc<T> {
                        type Response = super::InjectResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::InjectRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Hold>::inject(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = InjectSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hold.Hold/List" => {
                    #[allow(non_camel_case_types)]
                    struct ListSvc<T: Hold>(pub Arc<T>);
                    impl<T: Hold> tonic::server::UnaryService<super::ListRequest>
                    for ListSvc<T> {
                        type Response = super::ListResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Hold>::list(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hold.Hold/Settle" => {
                    #[allow(non_camel_case_types)]
                    struct SettleSvc<T: Hold>(pub Arc<T>);
                    impl<T: Hold> tonic::server::UnaryService<super::SettleRequest>
                    for SettleSvc<T> {
                        type Response = super::SettleResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SettleRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Hold>::settle(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SettleSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hold.Hold/Cancel" => {
                    #[allow(non_camel_case_types)]
                    struct CancelSvc<T: Hold>(pub Arc<T>);
                    impl<T: Hold> tonic::server::UnaryService<super::CancelRequest>
                    for CancelSvc<T> {
                        type Response = super::CancelResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CancelRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Hold>::cancel(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CancelSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hold.Hold/Clean" => {
                    #[allow(non_camel_case_types)]
                    struct CleanSvc<T: Hold>(pub Arc<T>);
                    impl<T: Hold> tonic::server::UnaryService<super::CleanRequest>
                    for CleanSvc<T> {
                        type Response = super::CleanResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CleanRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Hold>::clean(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CleanSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hold.Hold/Track" => {
                    #[allow(non_camel_case_types)]
                    struct TrackSvc<T: Hold>(pub Arc<T>);
                    impl<
                        T: Hold,
                    > tonic::server::ServerStreamingService<super::TrackRequest>
                    for TrackSvc<T> {
                        type Response = super::TrackResponse;
                        type ResponseStream = T::TrackStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TrackRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Hold>::track(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = TrackSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hold.Hold/TrackAll" => {
                    #[allow(non_camel_case_types)]
                    struct TrackAllSvc<T: Hold>(pub Arc<T>);
                    impl<
                        T: Hold,
                    > tonic::server::ServerStreamingService<super::TrackAllRequest>
                    for TrackAllSvc<T> {
                        type Response = super::TrackAllResponse;
                        type ResponseStream = T::TrackAllStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TrackAllRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Hold>::track_all(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = TrackAllSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hold.Hold/OnionMessages" => {
                    #[allow(non_camel_case_types)]
                    struct OnionMessagesSvc<T: Hold>(pub Arc<T>);
                    impl<
                        T: Hold,
                    > tonic::server::StreamingService<super::OnionMessageResponse>
                    for OnionMessagesSvc<T> {
                        type Response = super::OnionMessage;
                        type ResponseStream = T::OnionMessagesStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::OnionMessageResponse>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Hold>::onion_messages(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = OnionMessagesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for HoldServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "hold.Hold";
    impl<T> tonic::server::NamedService for HoldServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
